(in-package :stumpwm)

(set-prefix-key "C-z")

(defvar *my-keymap*
  (let ((m (make-sparse-keymap)))
    (define-key m "Q" "end-session")
    (define-key m "c-r" "loadrc")
    (define-key m "R" "reload")
    (define-key m "p" "exec rofi -font \"Inconsolata 14\" -show run")
    (define-key m "X" "exec rofi -font \"Inconsolata 14\" -show run")
    (define-key m "s-SPC" "float-this")
    (define-key m "SPC" "unfloat-this")
    (define-key m "c-SPC" "flatten-floats")
    (define-key m "l" "move-focus right")
    (define-key m "h" "move-focus left")
    (define-key m "k" "move-focus up")
    (define-key m "j" "move-focus down")
    (define-key m "L" "move-window right")
    (define-key m "H" "move-window left")
    (define-key m "K" "move-window up")
    (define-key m "J" "move-window down")
    (define-key m "c-h" "hsplit")
    (define-key m "c-v" "vsplit")
    (define-key m "r" "iresize")
    (define-key m "+" "balance-frames")
    (define-key m "d" "remove-split")
    (define-key m "D" "only")
    (define-key m "e" "expose")
    (define-key m "f" "fullscreen")
    (define-key m "i" "info")
    (define-key m "I" "show-window-properties")
    (define-key m "b" "windowlist")
    (define-key m "C" "delete-window")
    (define-key m "Q" "delete-window-and-frame")
    (define-key m "c-C" "kill-window") ; If delete-window didn't work, try this.
    m))

(define-key *root-map* '*my-keymap*)
(define-key *top-map* "s-RET") "term")
(define-key *top-map* "1") "gselect 1")
(define-key *top-map* "2") "gselect 2")
(define-key *top-map* "3") "gselect 3")
(define-key *top-map* "4") "gselect 4")
(define-key *top-map* "5") "gselect 5")
(define-key *top-map* "s-1") "gmove 1")
(define-key *top-map* "s-2") "gmove 2")
(define-key *top-map* "s-3") "gmove 3")
(define-key *top-map* "s-4") "gmove 4")
(define-key *top-map* "s-5") "gmove 5")
(define-key *root-map* "g" '*groups-map*)
(define-key *groups-map* "G" '*vgroups*)
(define-key *top-map* "s-TAB") "other-window")
(define-key *top-map* "O") "other-window")
