(in-package :stumpwm)

(set-prefix-key (kbd "F20")) ; mod4+
;(set-prefix-key (kbd "C-z"))

(define-key *root-map* (kbd "C-r") "loadrc")
(define-key *root-map* (kbd "R") "reload")
(define-key *root-map* (kbd "p") "exec rofi -font \"Inconsolata 14\" -show run")
(define-key *root-map* (kbd "S-SPC") "float-this")
(define-key *root-map* (kbd "SPC") "unfloat-this")
(define-key *root-map* (kbd "C-SPC") "flatten-floats")
(define-key *root-map* (kbd "l") "move-focus right")
(define-key *root-map* (kbd "h") "move-focus left")
(define-key *root-map* (kbd "k") "move-focus up")
(define-key *root-map* (kbd "j") "move-focus down")
(define-key *root-map* (kbd "L") "move-window right")
(define-key *root-map* (kbd "H") "move-window left")
(define-key *root-map* (kbd "K") "move-window up")
(define-key *root-map* (kbd "J") "move-window down")
(define-key *root-map* (kbd "C-h") "vsplit")
(define-key *root-map* (kbd "C-v") "hsplit")
(define-key *root-map* (kbd "r") "iresize")
(define-key *root-map* (kbd "+") "balance-frames")
(define-key *root-map* (kbd "d") "remove-split")
(define-key *root-map* (kbd "D") "only")
(define-key *root-map* (kbd "e") "expose")
(define-key *root-map* (kbd "f") "fullscreen")
(define-key *root-map* (kbd "i") "info")
(define-key *root-map* (kbd "I") "show-window-properties")
(define-key *root-map* (kbd "w") "frame-windowlist")
(define-key *root-map* (kbd "W") "windowlist")
(define-key *root-map* (kbd "b") "mode-line")
(define-key *root-map* (kbd "q") "delete-window")
(define-key *root-map* (kbd "Q") "delete-window-and-frame")
(define-key *root-map* (kbd "C") "kill-window") ; If delete-window didn't work, try this.
(define-key *root-map* (kbd "S-RET") "term")
(define-key *root-map* (kbd "1") "gselect 1")
(define-key *root-map* (kbd "2") "gselect 2")
(define-key *root-map* (kbd "3") "gselect 3")
(define-key *root-map* (kbd "4") "gselect 4")
(define-key *root-map* (kbd "5") "gselect 5")
(define-key *root-map* (kbd "6") "gselect 6")
(define-key *root-map* (kbd "7") "gselect 7")
(define-key *root-map* (kbd "8") "gselect 8")
(define-key *root-map* (kbd "9") "gselect 9")
(define-key *root-map* (kbd "0") "gselect 0")
(define-key *root-map* (kbd "!") "gmove 1")
(define-key *root-map* (kbd "@") "gmove 2")
(define-key *root-map* (kbd "#") "gmove 3")
(define-key *root-map* (kbd "$") "gmove 4")
(define-key *root-map* (kbd "%") "gmove 5")
(define-key *root-map* (kbd "^") "gmove 6")
(define-key *root-map* (kbd "&") "gmove 7")
(define-key *root-map* (kbd "*") "gmove 8")
(define-key *root-map* (kbd "(") "gmove 9")
(define-key *root-map* (kbd ")") "gmove 0")
