
################################################################################
# Author: Andy Nagels
# Date: 2015-03-04
#
# .xinitrc:
# Settings, to be loaded when the X-server starts.
################################################################################

xinitrc_settigs_general.sh &
xinitrc_settings_language.sh &
xinitrc_custom_scripts.sh &
startwm.sh
