setxkbmap us -variant colemak &
urxvtd &
xrdb -nocpp -merge ~/.Xresources
wallpaper &
#xset s off
export LANG=ja_JP.UTF-8 LLC_ALL=ja_JP.UTF-8
export GTK_IM_MODULE='uim'
export QT_IM_MODULE='uim'
export XMODIFIERS=@im='uim'
uim-xim &
timetokyo &
startwm
